{{- if and .Values.ingress.enabled .Values.adminWeb.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myota
  labels:
    app.kubernetes.io/name: myota
    app.kubernetes.io/component: ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myota-admin-web
                port:
                  number: {{ .Values.adminWeb.servicePort }}
{{- end }}
