apiVersion: batch/v1
kind: Job
metadata:
  name: myota-migrations-{{ .Release.Revision }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/bash", "/app/db/migrations/run.sh"]
          env:
            - name: CORE_HOST
              value: {{ .Values.postgres.coreHost | quote }}
            - name: CORE_PORT
              value: {{ .Values.postgres.corePort | quote }}
            - name: ACTIVITY_HOST
              value: {{ .Values.postgres.activityHost | quote }}
            - name: ACTIVITY_PORT
              value: {{ .Values.postgres.activityPort | quote }}
            - name: GEO_HOST
              value: {{ .Values.postgres.geoHost | quote }}
            - name: GEO_PORT
              value: {{ .Values.postgres.geoPort | quote }}
            - name: PGUSER
              valueFrom: {secretKeyRef: {name: {{ .Values.postgres.existingSecret }}, key: username}}
            - name: PGPASSWORD
              valueFrom: {secretKeyRef: {name: {{ .Values.postgres.existingSecret }}, key: password}}
            - name: CORE_DATABASE
              value: {{ .Values.postgres.coreDatabase | quote }}
            - name: ACTIVITY_DATABASE
              value: {{ .Values.postgres.activityDatabase | quote }}
            - name: GEO_DATABASE
              value: {{ .Values.postgres.geoDatabase | quote }}
            - name: LEGACY_GEO_HOST
              value: {{ .Values.postgres.coreHost | quote }}
            - name: LEGACY_GEO_PORT
              value: {{ .Values.postgres.corePort | quote }}
            - name: LEGACY_GEO_DATABASE
              value: {{ .Values.postgres.geoDatabase | quote }}
